const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('assert/strict'),fs=require('fs');
const routes=['/','/services','/services/professional-learning','/services/computer-science','/services/ai-emerging-technology','/services/curriculum-product-development','/work','/work/district-16','/work/mouse-ai-fluency','/work/exact-path','/work/school-meal-platform','/work/cornell-tech','/about','/resources','/contact','/privacy'];
(async()=>{const b=await chromium.launch();const p=await b.newPage();let errors=[]; p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('500'))errors.push(m.text())});
let links=new Set();
for(const width of [1440,768,390,320]){await p.setViewportSize({width,height:900});for(const route of routes){const r=await p.goto('http://127.0.0.1:8765'+route);assert.equal(r.status(),200,route);assert.equal((await p.reload()).status(),200);assert.equal(await p.locator('h1').count(),1);assert(await p.locator('meta[name=description]').getAttribute('content'));assert((await p.locator('link[rel=canonical]').getAttribute('href')).startsWith('https://palmchat.io/'));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width} ${route}`);assert.deepEqual(await p.locator('img').evaluateAll(a=>a.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)),[]);for(const href of await p.locator('a[href]').evaluateAll(a=>a.map(x=>x.getAttribute('href'))))if(href.startsWith('/')&&!href.includes('?'))links.add(href);if(width===1440&&['/','/work','/about','/contact','/resources'].includes(route))await p.screenshot({path:require('node:os').tmpdir()+'/palmchat-review-'+(route.slice(1)||'home')+'.png',fullPage:true});if(width===390&&route==='/')await p.screenshot({path:require('node:os').tmpdir()+'/palmchat-review-mobile.png',fullPage:true});}}
for(const href of links){assert.equal((await p.request.get('http://127.0.0.1:8765'+href)).status(),200,href)}
await p.setViewportSize({width:390,height:844});await p.goto('http://127.0.0.1:8765');const menu=p.locator('.menu-button');await menu.click();assert.equal(await menu.getAttribute('aria-expanded'),'true');await p.keyboard.press('Escape');assert.equal(await menu.getAttribute('aria-expanded'),'false');assert(await menu.evaluate(e=>e===document.activeElement));await menu.click();await p.locator('#site-nav a[href="/services"]').click();assert(p.url().endsWith('/services'));assert.equal(await menu.getAttribute('aria-expanded'),'false');await p.locator('summary').first().click();assert(await p.locator('details').first().getAttribute('open')!==null);
await p.goto('http://127.0.0.1:8765/contact');assert.equal(await p.locator('form').count(),0);assert.equal(await p.getByRole('link',{name:'Email Edwin'}).getAttribute('href'),'mailto:erjaquez@gmail.com');
await p.emulateMedia({reducedMotion:'reduce'});await p.goto('http://127.0.0.1:8765');assert.equal(await p.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');await p.locator('.text-link').first().hover();assert.equal(await p.locator('.text-link span').first().evaluate(e=>getComputedStyle(e).transform),'none');await p.keyboard.press('Tab');assert(await p.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle!=='none'));
assert.deepEqual(errors.filter(e=>!e.includes('ERR_FAILED')),[]);console.log(JSON.stringify({routes:routes.length,widths:[1440,768,390,320],links:links.size,liveSubmissions:0,errors,passed:true},null,2));await b.close()})().catch(e=>{console.error(e);process.exit(1)});
