import { mkdirSync, writeFileSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const write = (path, content) => {
  const url = new URL(path, root);
  mkdirSync(new URL('./', url), { recursive: true });
  writeFileSync(url, content.trimStart());
};

const navItems = [['Home','/'],['Services','/services'],['Work','/work'],['About','/about'],['Resources','/resources'],['Contact','/contact']];
const titleMap = {
  home:'PalmChat Innovations | Education and Learning Design', services:'Services | PalmChat Innovations', work:'Selected Work | PalmChat Innovations',
  about:'About Edwin Jaquez | PalmChat Innovations', resources:'Resources | PalmChat Innovations', contact:'Contact PalmChat Innovations'
};

function shell({ key, title, description, path, body, bodyClass='' }) {
  const pageTitle = title || titleMap[key];
  const canonical = `https://palmchat.io${path}`;
  const nav = navItems.map(([label,href]) => `<a href="${href}"${key === label.toLowerCase() ? ' aria-current="page"' : ''}>${label}</a>`).join('');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${pageTitle}</title><meta name="description" content="${description}"><meta name="theme-color" content="#4F683E"><link rel="canonical" href="${canonical}">
<link rel="icon" href="/assets/brand/favicon-v2.svg"><link rel="apple-touch-icon" href="/assets/brand/apple-touch-icon-v2.png"><link rel="stylesheet" href="/styles.css">
<meta property="og:type" content="website"><meta property="og:site_name" content="PalmChat Innovations"><meta property="og:title" content="${pageTitle}"><meta property="og:description" content="${description}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="https://palmchat.io/assets/social/palmchat-preview-v2.png"><meta name="twitter:card" content="summary_large_image">
</head><body class="${bodyClass}"><a class="skip-link" href="#main-content">Skip to content</a>
<header class="site-header"><div class="shell header-inner"><a class="brand" href="/" aria-label="PalmChat Innovations home"><img src="/assets/brand/palmchat-mark-v2.svg" alt="" width="46" height="46"><span><strong>PalmChat Innovations</strong><small>Education + Learning Design</small></span></a><button class="menu-button" type="button" aria-expanded="false" aria-controls="site-nav"><span></span><span></span><span></span><b>Menu</b></button><nav id="site-nav" class="site-nav" aria-label="Main navigation">${nav}<a class="nav-action" href="/contact">Start a conversation</a></nav></div></header>
<main id="main-content">${body}</main>
<footer class="site-footer"><div class="shell footer-main"><div><a class="footer-name" href="/">PalmChat Innovations LLC</a><p>Founder-led education + learning design.</p></div><nav aria-label="Footer navigation">${nav}</nav><div class="footer-meta"><a href="mailto:erjaquez@gmail.com">erjaquez@gmail.com</a><span>English + Spanish</span><a href="/privacy">Privacy</a></div></div><div class="shell footer-base"><span>© <span data-year></span> PalmChat Innovations LLC</span><span>Practical · Rigorous · Joyful · Inclusive</span></div></footer><script src="/script.js" defer></script></body></html>`;
}

const arrow = '<span aria-hidden="true">↗</span>';
const cta = (heading='Build the next step with purpose.') => `<section class="band-cta"><div class="shell"><p class="overline">Start a conversation</p><h2>${heading}</h2><a class="text-link light" href="/contact">Work with PalmChat ${arrow}</a></div></section>`;
const pageHero = (number,kicker,title,intro,extra='') => `<section class="page-hero"><div class="shell page-hero-grid"><div><p class="section-number">${number}</p><p class="overline">${kicker}</p></div><div><h1>${title}</h1><p class="dek">${intro}</p>${extra}</div></div></section>`;

const services = [
  {slug:'professional-learning',number:'01',name:'Professional Learning',short:'Build confidence through relevant, hands-on learning.',desc:'Workshops, coaching, facilitation, and implementation support that connect learning to everyday practice.',audience:'Schools, district teams, education nonprofits, and teacher leaders.',problem:'Educators and leaders need practical support that respects their expertise, time, and context.',deliver:'PalmChat designs and facilitates learning that makes priorities actionable without adding unnecessary complexity.',formats:['Interactive workshops','Professional learning series','Coaching cycles','Leadership facilitation','Implementation support'],leaves:'Clear next steps, usable resources, shared language, and a stronger foundation for sustained practice.'},
  {slug:'computer-science',number:'02',name:'Computer Science Program Design',short:'Create coherent, sustainable computer science pathways.',desc:'Program strategy, curriculum design, computational thinking integration, and implementation planning for K–12 learning.',audience:'Schools and districts building or strengthening K–12 computer science experiences.',problem:'Sustainable computer science requires more than a tool or isolated course; it needs coherence, teacher support, and ownership.',deliver:'PalmChat helps teams shape a clear program vision, connect curriculum to practice, and plan for implementation.',formats:['Program planning','Curriculum mapping','Scope and sequence design','Teacher coaching','Computational thinking integration'],leaves:'A practical roadmap, aligned learning experiences, and tools educators and leaders can carry forward.'},
  {slug:'ai-emerging-technology',number:'03',name:'AI and Emerging Technology',short:'Navigate new technology with purpose, care, and practical guardrails.',desc:'AI literacy, prompt development, ethical use, classroom applications, and tool-agnostic professional learning.',audience:'Schools, adult-learning teams, and education organizations exploring responsible AI use.',problem:'Teams need room to learn and experiment while keeping ethics, bias, access, privacy, and learning goals in view.',deliver:'PalmChat creates approachable experiences that help educators evaluate tools, develop prompts, discuss risks, and connect use to real needs.',formats:['AI fluency workshops','Prompt-development labs','Leadership briefings','Ethics and guardrail sessions','Implementation planning'],leaves:'Shared understanding, useful frameworks, practical examples, and clearer decisions about responsible adoption.'},
  {slug:'curriculum-product-development',number:'04',name:'Curriculum and Product Development',short:'Turn strong ideas into useful learning experiences.',desc:'Instructional design, curriculum development, resource creation, and education product consulting.',audience:'Nonprofits, education companies, founders, and mission-driven product teams.',problem:'Promising ideas need coherent learning flow, credible instructional design, and attention to the people who will use them.',deliver:'PalmChat connects product strategy with curriculum thinking, stakeholder needs, usability, and implementation realities.',formats:['Curriculum design','Learning-experience design','Product consulting','Resource development','Facilitation and feedback synthesis'],leaves:'A clearer learning journey, stakeholder-ready materials, and a more usable, instructionally grounded experience.'}
];

const projects = [
  {slug:'district-16',number:'01',name:'School Leadership Professional Learning',category:'Professional Learning · Leadership',short:'Moving from district priorities to school-level action, ownership, monitoring, and student growth.',context:'School leaders were working to translate shared district priorities into coherent action across individual school communities.',challenge:'The work required a practical bridge between broad priorities and the routines, decisions, ownership, and evidence leaders could use at the school level.',role:'Professional learning designer and facilitator supporting leadership teams.',approach:'Facilitated collaborative learning and planning that connected strategic priorities to school-level ownership, implementation routines, and evidence of progress.',deliverables:['Leadership workshops','Planning conversations','Implementation frameworks','Monitoring tools'],methods:['Facilitation','Strategic planning','Instructional leadership','Stakeholder engagement'],impact:'Designed to support clearer ownership, visible next steps, and stronger alignment between leadership action and student growth.',related:['mouse-ai-fluency','cornell-tech']},
  {slug:'mouse-ai-fluency',number:'02',name:'AI Fluency Professional Learning',category:'AI Integration · Professional Learning',short:'Building AI literacy through prompting, ethical use, bias, guardrails, and classroom application.',context:'Educators were exploring generative AI while navigating fast-moving tools, uneven familiarity, and important questions about classroom use.',challenge:'Participants needed a practical learning experience that moved beyond hype while making space for experimentation, ethics, bias, and responsible guardrails.',role:'AI literacy learning designer and professional learning facilitator.',approach:'Combined hands-on prompting, reflection, and discussion of classroom relevance with attention to equity, bias, ethical use, and learning goals.',deliverables:['AI fluency sessions','Prompting frameworks','Discussion guides','Ethical-use resources'],methods:['Prompt development','Hands-on exploration','Ethics protocols','Educator coaching'],impact:'Designed to help educators evaluate, use, and discuss AI with greater clarity and purpose.',related:['district-16','exact-path']},
  {slug:'exact-path',number:'03',name:'Adaptive Learning Professional Learning',category:'Professional Learning · Curriculum Design',short:'Connecting adaptive-learning data to implementation practice and student support.',context:'Educators and leaders were working with adaptive learning information in the context of broader instructional priorities.',challenge:'Digital tools can be underused when teams lack time, context, and a shared implementation approach for translating data into instructional decisions.',role:'Professional learning designer and facilitator.',approach:'Grounded learning in data interpretation, instructional use, planning, and the routines educators need to connect platform information to classroom decisions.',deliverables:['Facilitated learning sessions','Implementation guidance','Educator materials','Leadership planning support'],methods:['Data-informed instruction','Adaptive-learning support','Learning design','Facilitation'],impact:'Focused on helping teams use adaptive-learning tools more strategically and consistently in support of student growth.',related:['mouse-ai-fluency','cornell-tech']},
  {slug:'school-meal-platform',number:'04',name:'School Meal Operations Platform',category:'Product Development · Learning Experience Design',short:'PalmChat designed and developed an education platform that brings together school-based operations, user workflows, administrative tools, and reporting in one streamlined experience.',context:'This engagement brought together education product strategy, school operations technology, interface development, and role-based platform planning.',challenge:'The work required a coherent product experience for school-based operations without exposing private workflows, business rules, student information, or proprietary requirements.',role:'Education product strategist, user-experience designer, workflow designer, and full-stack product developer.',approach:'Developed the platform at a capability level around user experience, administrative tools, reporting concepts, and operational problem-solving. Public details remain intentionally limited.',deliverables:['Education product strategy','User experience design','Interface development','Role-based platform planning'],methods:['Workflow design','Administrative-tool planning','Reporting concepts','Full-stack product development'],impact:'Designed to support a more streamlined operational experience while protecting confidential product and school information.',note:'The public case study is intentionally anonymized. It does not include the company, actual screens, product branding, student information, internal workflows, business rules, database structure, proprietary requirements, or unreleased features.',related:['exact-path','mouse-ai-fluency']},
  {slug:'cornell-tech',number:'05',name:'K–12 Computer Science Coaching',category:'Computer Science · Professional Learning',short:'Supporting K–8 educators with CS integration, computational thinking, and classroom practice.',context:'K–8 educators were working to bring computer science and computational thinking into varied classroom contexts.',challenge:'Teachers needed practical support translating broad computer science goals into instructionally sound experiences they could adapt and sustain.',role:'Computer science coach and professional learning facilitator.',approach:'Combined coaching, classroom support, collaborative planning, and professional learning to connect computational thinking with day-to-day instruction.',deliverables:['Coaching cycles','Professional development','Planning support','Integration resources'],methods:['Computer science pedagogy','Computational thinking','Teacher coaching','Curriculum integration'],impact:'Designed to strengthen teacher confidence and support sustainable computer science practice.',related:['district-16','exact-path']}
];

const home = shell({key:'home',path:'/',description:'PalmChat Innovations helps schools and education organizations design meaningful computer science, professional learning, curriculum, and AI integration experiences.',bodyClass:'home',body:`
<section class="home-hero"><div class="shell home-hero-grid"><div class="hero-copy"><p class="overline">Founder-led education + learning design</p><h1>Practical innovation for stronger teaching and learning.</h1><p class="dek">PalmChat Innovations helps schools and education organizations design meaningful computer science, professional learning, curriculum, and AI integration experiences.</p><div class="actions"><a class="button dark" href="/work">Explore the work</a><a class="text-link" href="/contact">Start a conversation ${arrow}</a></div></div><div class="hero-signature"><span>Learning, made practical.</span><p>With Edwin Jaquez<br>Educator &amp; founder</p></div></div></section>
<section class="positioning"><div class="shell split-statement"><p class="section-number">01 / Approach</p><h2>Strategy is only useful when it becomes practice.</h2><div><p>PalmChat brings an educator’s perspective to program design, facilitation, curriculum, and emerging technology.</p><a class="text-link" href="/about">About Edwin ${arrow}</a></div></div></section>
<section class="services-preview"><div class="shell"><div class="section-intro"><p class="section-number">02 / Services</p><h2>Clear support for meaningful learning.</h2><a class="text-link" href="/services">Explore services ${arrow}</a></div><div class="service-links">${services.map(s=>`<a href="/services/${s.slug}"><span>${s.number}</span><strong>${s.name}</strong>${arrow}</a>`).join('')}</div></div></section>
<section class="selected-work"><div class="shell"><div class="section-intro"><p class="section-number">03 / Selected work</p><h2>Learning experiences built for real contexts.</h2><a class="text-link" href="/work">View all work ${arrow}</a></div><div class="home-projects">${projects.filter(p=>['district-16','mouse-ai-fluency','school-meal-platform'].includes(p.slug)).map((p,i)=>`<article class="home-project project-${i+1}"><span class="project-count">0${i+1}</span><div><p>${p.category}</p><h3><a href="/work/${p.slug}">${p.name}</a></h3><p>${p.short}</p><a class="text-link" href="/work/${p.slug}">View case study ${arrow}</a></div></article>`).join('')}</div></div></section>
<section class="founder-teaser"><div class="shell founder-teaser-grid"><div class="ej-mark" aria-hidden="true"><span>EJ</span><small>Founder · Educator · Designer</small></div><div><p class="section-number">04 / Founder</p><h2>Grounded in classrooms. Built for what comes next.</h2><p>Edwin Jaquez brings experience as an educator, computer science teacher, instructional and school-culture leader, consultant, and product builder.</p><a class="text-link light" href="/about">Meet Edwin ${arrow}</a></div></div></section>${cta('Let’s make the next idea useful, human, and ready for practice.')}`});
write('index.html', home);

const serviceRows = services.map(s=>`<article class="service-row"><span>${s.number}</span><div><h2><a href="/services/${s.slug}">${s.name}</a></h2><p>${s.desc}</p><details><summary>How PalmChat can help</summary><p>${s.problem}</p><p>${s.deliver}</p></details></div><div><p><strong>Best fit</strong>${s.audience}</p><p><strong>Engagements</strong>${s.formats.slice(0,3).join(' · ')}</p><a class="text-link" href="/services/${s.slug}">Explore ${s.name.toLowerCase()} ${arrow}</a></div></article>`).join('');
write('services/index.html', shell({key:'services',path:'/services',description:'Professional learning, computer science program design, AI integration, curriculum, and product-development services from PalmChat Innovations.',bodyClass:'services-index',body:`${pageHero('01','Services','Designed around the work, not a template.','PalmChat partners with education teams to clarify the challenge, build practical capacity, and create experiences people can use and sustain.')}<section class="service-ledger"><div class="shell">${serviceRows}</div></section>${cta()}`}));

for (const s of services) {
  write(`services/${s.slug}.html`, shell({key:'services',title:`${s.name} | PalmChat Innovations`,path:`/services/${s.slug}`,description:`${s.desc} PalmChat Innovations supports education teams with practical, context-aware design.`,bodyClass:'service-detail',body:`${pageHero(`01 / ${s.number}`,'Service',s.name,s.short,`<a class="text-link" href="/contact">Discuss an engagement ${arrow}</a>`)}<section class="detail-story"><div class="shell detail-story-grid"><aside><p class="overline">What it is</p><p>${s.desc}</p><p class="overline">Who it is for</p><p>${s.audience}</p></aside><div class="detail-sections"><section><span>01</span><h2>The problem it addresses</h2><p>${s.problem}</p></section><section><span>02</span><h2>What PalmChat delivers</h2><p>${s.deliver}</p></section><section><span>03</span><h2>Possible formats</h2><ul class="plain-list">${s.formats.map(x=>`<li>${x}</li>`).join('')}</ul></section><section><span>04</span><h2>Designed to support</h2><p>${s.leaves}</p></section></div></div></section><nav class="next-service shell" aria-label="Other services"><p>Explore another service</p>${services.filter(x=>x.slug!==s.slug).map(x=>`<a href="/services/${x.slug}">${x.name} ${arrow}</a>`).join('')}</nav>${cta(`Ready to explore ${s.name.toLowerCase()}?`)}`}));
}

const workRows = projects.map(p=>`<article class="work-row"><span class="project-count">${p.number}</span><div><p class="project-category">${p.category}</p><h2><a href="/work/${p.slug}">${p.name} ${arrow}</a></h2><p>${p.short}</p><a class="text-link" href="/work/${p.slug}">Read the case study ${arrow}</a></div></article>`).join('');
write('work/index.html', shell({key:'work',path:'/work',description:'Selected professional learning, computer science, AI integration, curriculum, leadership, and product-development work from PalmChat Innovations.',bodyClass:'work-index',body:`${pageHero('02','Selected work','Different contexts. A consistent commitment to useful learning.','A portfolio of facilitation, coaching, program design, curriculum, AI integration, and product work.')}<section class="work-list"><div class="shell">${workRows}</div></section>${cta('Bring a real challenge. We’ll shape the right next step.')}`}));

for (const p of projects) {
  const related = p.related.map(slug=>projects.find(x=>x.slug===slug)).filter(Boolean);
  write(`work/${p.slug}.html`, shell({key:'work',title:`${p.name} | PalmChat Innovations`,path:`/work/${p.slug}`,description:`${p.short} A PalmChat Innovations project.`,bodyClass:'case-study',body:`<section class="case-hero"><div class="shell"><div class="case-meta"><p>${p.number} / Case study</p><p>${p.category}</p></div><h1>${p.name}</h1><p class="dek">${p.short}</p></div></section><section class="case-narrative"><div class="shell case-narrative-grid"><aside><p class="overline">PalmChat role</p><p>${p.role}</p><p class="overline">Context</p><p>${p.context}</p></aside><div><section><span>01</span><h2>Challenge</h2><p>${p.challenge}</p></section><section><span>02</span><h2>Approach</h2><p>${p.approach}</p></section><section><span>03</span><h2>Deliverables</h2><ul class="plain-list">${p.deliverables.map(x=>`<li>${x}</li>`).join('')}</ul></section><section><span>04</span><h2>Tools + methods</h2><ul class="plain-list">${p.methods.map(x=>`<li>${x}</li>`).join('')}</ul></section><section><span>05</span><h2>Intended impact</h2><p>${p.impact}</p>${p.note?`<p class="confidentiality"><strong>Confidentiality note</strong>${p.note}</p>`:''}</section></div></div></section><section class="related"><div class="shell"><p class="overline">Related projects</p><div>${related.map(r=>`<a href="/work/${r.slug}"><span>${r.category}</span><strong>${r.name}</strong>${arrow}</a>`).join('')}</div></div></section>${cta('Have a project that needs clarity, momentum, or design support?')}`}));
}

write('about/index.html', shell({key:'about',path:'/about',description:'Meet Edwin Jaquez, educator, computer science teacher, learning designer, consultant, and founder of PalmChat Innovations.',bodyClass:'about-page',body:`${pageHero('03','About Edwin','Educator first. Designer always.','Edwin Jaquez founded PalmChat Innovations to help education teams turn promising ideas into learning people can understand, use, and sustain.')}<section class="about-profile"><div class="shell about-profile-grid"><div><div class="ej-portrait" role="img" aria-label="EJ monogram for Edwin Jaquez"><span>EJ</span><small>Founder · Educator · Designer</small></div></div><div class="bio"><p class="lead-copy">Edwin is an educator, computer science teacher, school culture and instructional leader, professional learning consultant, curriculum and program designer, AI and emerging technology facilitator, and founder building education products.</p><p>His perspective is shaped by the work of teaching, leading, coaching, facilitating, and designing alongside the people responsible for bringing ideas into practice.</p><p>PalmChat creates room for rigorous thinking and approachable learning. The goal is not technology for its own sake, but clearer decisions, stronger experiences, and programs that make sense in the environments where they will live.</p><div class="philosophy"><p class="overline">Learning philosophy</p><p>Joyful. Rigorous. Practical. Inclusive.</p></div><div class="language-note"><span>Languages</span><strong>English + Spanish</strong></div></div></div></section><section class="experience-ledger"><div class="shell"><p class="overline">Professional perspective</p>${[['01','Classroom + computer science','Experience teaching and supporting computer science, computational thinking, and interdisciplinary classroom integration.'],['02','Leadership + professional learning','School culture, instructional leadership, facilitation, coaching, and adult learning designed around actionable practice.'],['03','Curriculum + programs','Curriculum, resources, scopes and sequences, implementation planning, and coherent program experiences.'],['04','AI + emerging technology','AI literacy, prompting, ethics, bias, guardrails, classroom application, and tool-agnostic learning.'],['05','Education products','Learning-experience and product design grounded in usability, stakeholder needs, and implementation realities.']].map(x=>`<article><span>${x[0]}</span><h2>${x[1]}</h2><p>${x[2]}</p></article>`).join('')}</div></section>${cta('Work with a founder who understands the classroom and the design table.')}`}));

write('resources/index.html', shell({key:'resources',path:'/resources',description:'PalmChat resources on AI fluency, computer science integration, professional learning, curriculum, and education technology are in development.',bodyClass:'resources-page',body:`<section class="resources-hero"><div class="shell resources-grid"><div><p class="section-number">04 / Resources</p><p class="overline">In development</p><h1>Practical ideas are on the way.</h1><p class="dek">PalmChat resources are being developed around AI fluency, computer science integration, professional learning, curriculum, and education technology.</p><div class="actions"><a class="button light" href="mailto:erjaquez@gmail.com?subject=PalmChat%20resource%20updates">Request updates</a><a class="text-link light" href="/contact">Start a conversation ${arrow}</a></div></div><div class="resource-composition" aria-hidden="true"><span>Think.</span><span>Try.</span><span>Reflect.</span><span>Repeat.</span></div></div></section><section class="resource-note"><div class="shell split-statement"><p class="section-number">What to expect</p><h2>Useful enough to bring into the room.</h2><p>Future resources will prioritize practical frameworks, discussion tools, and learning materials. Have a topic in mind? Let Edwin know what would be useful to your team.</p></div></section>`}));

write('contact/index.html', shell({key:'contact',path:'/contact',description:'Contact PalmChat Innovations about professional learning, computer science, AI integration, curriculum, facilitation, or product design.',bodyClass:'contact-page',body:`${pageHero('05','Contact','What are you working toward?','Share the context, the challenge, or simply the question. PalmChat will help identify a useful next step.')}<section class="contact-section"><div class="shell contact-layout"><aside><p class="overline">Direct contact</p><a class="large-email" href="mailto:erjaquez@gmail.com">erjaquez@gmail.com</a><dl><div><dt>Based in</dt><dd>New York City</dd></div><div><dt>Available for</dt><dd>Remote and travel engagements</dd></div><div><dt>Who PalmChat supports</dt><dd>Schools, districts, nonprofits, education companies, and learning teams</dd></div></dl></aside><div class="contact-invitation"><p class="overline">Let’s start with an email</p><h2>A question is a good place to begin.</h2><p>Tell Edwin a little about your team, what you’re working on, and the support you have in mind. If you have a timeline, include that too.</p><a class="button" href="mailto:erjaquez@gmail.com">Email Edwin ${arrow}</a></div></div></section>`}));

write('privacy.html', shell({key:'',title:'Privacy | PalmChat Innovations',path:'/privacy',description:'Privacy information for the PalmChat Innovations website.',bodyClass:'legal-page',body:`${pageHero('','Privacy','Privacy information','Contact PalmChat Innovations directly by email with questions about your information.')}<article class="shell legal-copy"><h2>Email inquiries</h2><p>This website does not collect inquiries through a contact form. Email links open your email application so you can contact Edwin directly at erjaquez@gmail.com. Please avoid including sensitive student or confidential information.</p><h2>How information is used</h2><p>Inquiry information is used to understand your request and respond. It is not presented publicly or used to create public claims without permission.</p><h2>Questions</h2><p>Email <a href="mailto:erjaquez@gmail.com">erjaquez@gmail.com</a>.</p></article>`}));

console.log('Generated PalmChat multi-page site.');
